---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ingester
spec:
  replicas: 1

  # Ingesters are not ready for at least 1 min
  # after creation.  This has to be in sync with
  # the ring timeout value, as this will stop a
  # stampede of new ingesters if we should loose
  # some.
  minReadySeconds: 60

  # Having maxSurge 0 and maxUnavailable 1 means
  # the deployment will update one ingester at a time
  # as it will have to stop one (making one unavailable)
  # before it can start one (surge of zero)
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1

  template:
    metadata:
      labels:
        name: ingester
    spec:
      # Give ingesters 40 minutes grace to flush chunks and exit cleanly.
      # Service is available during this time, as long as we don't stop
      # too many ingesters at once.
      terminationGracePeriodSeconds: 2400

      containers:
      - name: ingester
        image: quay.io/cortexproject/ingester:master-07dc4f31
        imagePullPolicy: IfNotPresent
        args:
        - -event.sample-rate=100
        - -ingester.join-after=30s
        - -ingester.claim-on-rollout=true
        - -ingester.max-chunk-age=12h
        - -ingester.max-chunk-idle=10m
        - -ingester.retain-period=10m10s
        - -consul.hostname=consul.cortex.svc.cluster.local:8500
        - -cassandra.keyspace=weave
        - -cassandra.addresses=redacted
        - -cassandra.port=10350
        - -cassandra.ssl=true
        - -cassandra.host-verification=false
        - -cassandra.auth=true
        - -cassandra.username=redacted
        - -cassandra.password=redacted
        - -config-yaml=/etc/config/schema.yaml
        - -store.index-cache-write.memcached.hostname=memcached.cortex.svc.cluster.local.
        - -store.index-cache-write.memcached.expiration=24h
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /ready
            port: 80
          initialDelaySeconds: 15
          timeoutSeconds: 1
        volumeMounts:
        - name: schema-volume
          mountPath: /etc/config
      volumes:
      - name: schema-volume
        configMap:
          name: schema-config
