---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: querier
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: querier
    spec:
      containers:
      - name: querier
        image: quay.io/cortexproject/querier:master-07dc4f31
        imagePullPolicy: IfNotPresent
        args:
        - -server.http-listen-port=80
        - -consul.hostname=consul:8500
        - -cassandra.keyspace=weave
        - -cassandra.addresses=redacted
        - -cassandra.port=10350
        - -cassandra.ssl=true
        - -cassandra.timeout=5s
        - -cassandra.host-verification=false
        - -cassandra.auth=true
        - -cassandra.username=redacted
        - -cassandra.password=redacted
        - -config-yaml=/etc/config/schema.yaml
        - -memcached.hostname=memcached
        - -memcached.timeout=100ms
        - -memcached.service=memcached
        - -index.memcached.hostname=memcached.cortex.svc.cluster.local.
        - -index.memcached.timeout=10s
        - -distributor.replication-factor=1
        ports:
        - containerPort: 80
        volumeMounts:
        - name: schema-volume
          mountPath: /etc/config
      volumes:
      - name: schema-volume
        configMap:
          name: schema-config
